// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (typeof window !== "undefined") {
  // Debug: Log env variables in browser
  console.log("[Supabase] VITE_SUPABASE_URL:", SUPABASE_URL);
  console.log("[Supabase] VITE_SUPABASE_ANON_KEY:", SUPABASE_ANON_KEY);
}

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error(
    "Supabase environment variables are missing. Check your .env file and restart the server.",
  );
}

// NOTE: If Supabase JWT secrets are rotated, ensure any backend services that validate Supabase tokens
// use the new secret. For frontend-only Vite apps, no change is needed unless you have custom backend validation.
// If you add backend validation, load the new JWT secret from environment variables securely.

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
